version: '2'
services:
    php:
        build: ./.docker/php
        volumes:
            - ./:/var/www/html
        environment:
            - PRODUCTION=false
    nginx:
        image: nginx:1.11.6
        volumes:
            - ./web:/usr/share/nginx/html
            - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 81:80
    mysql:
        image: mariadb:10.1
        volumes:
            - ~/listeattente_docker_volumes/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=listeattente
            - MYSQL_USER=listeattente
            - MYSQL_PASSWORD=listeattente
    composer:
        image: composer/composer:1.1
        volumes:
            - ./:/app
