sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
services:
    admin.patient:
        class: AppBundle\Admin\PatientAdmin
        arguments: [~, AppBundle\Entity\Patient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Patient }